### ISSUE TITLE
Saya belum dapat mencoba menjalankan request

### ISSUE THREAD

**Issue by TaqiyuddinJ** [youhane/chrombit_assessment#1]
saya sudah berhasil menjalankan kodenya di terminal dan sudah menampilkan
```
🚀 Succeed Running On http://localhost:3000

 ┌───────────────────────────────────────────────────┐
 │                   Fiber v2.48.0                   │
 │               http://127.0.0.1:3000               │
 │       (bound on host 0.0.0.0 and port 3000)       │
 │                                                   │
 │ Handlers ............ 12  Processes ........... 1 │
 │ Prefork ....... Disabled  PID ............. 25000 │
 └───────────────────────────────────────────────────┘
```

Tetapi ketika saya mencoba melakukan http request untuk register: POST `http://127.0.0.1:3000/api/v1/register`
dengan badan JSON
```
{
  "user_email":"taqiyuddin.j@gmail.com",
  "user_password":"default123!"
}
```
respon yang saya dapatkan justru `500 Internal Server Error` `runtime error: invalid memory address or nil pointer dereference`

**Comment by youhane** [comment]
> saya sudah berhasil menjalankan kodenya di terminal dan sudah menampilkan
> 
> ```
> 🚀 Succeed Running On http://localhost:3000
> 
>  ┌───────────────────────────────────────────────────┐
>  │                   Fiber v2.48.0                   │
>  │               http://127.0.0.1:3000               │
>  │       (bound on host 0.0.0.0 and port 3000)       │
>  │                                                   │
>  │ Handlers ............ 12  Processes ........... 1 │
>  │ Prefork ....... Disabled  PID ............. 25000 │
>  └───────────────────────────────────────────────────┘
> ```
> 
> Tetapi ketika saya mencoba melakukan http request untuk register: POST `http://127.0.0.1:3000/api/v1/register` dengan badan JSON
> 
> ```
> {
>   "user_email":"taqiyuddin.j@gmail.com",
>   "user_password":"default123!"
> }
> ```
> 
> respon yang saya dapatkan justru `500 Internal Server Error` `runtime error: invalid memory address or nil pointer dereference`

Dapat dicoba lebih lanjut pada branch postgres-validate, yang menggunakan database yang terhosted, dikarenakan saat dicoba pada mesin yang berbeda tetap berjalan dari pihak saya.

Berikut env yang dapat digunakan, env ini akan berlaku hingga Sabtu, 2 September 2023

PORT=":3000"

DB_HOST="ep-tiny-rain-25774450.ap-southeast-1.aws.neon.tech"
DB_NAME="neondb"
DB_USER= "youhane"
DB_PASSWORD= "iG7RMmK9UJuH"
DB_PORT="5432"

API_SECRET=2b7e151628aed2a6abf7158809cf4f3c
API_IV=2b7e151628aed2a6

Terima kasih
